package bean;
// Generated Jun 27, 2018 7:35:54 AM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * NhanVien generated by hbm2java
 */
public class NhanVien  implements java.io.Serializable {


     private int manv;
     private String tennv;
     private String diachi;
     private String gioitinh;

    public NhanVien() {
    }

    public NhanVien(String tennv, String diachi, String gioitinh) {
        this.tennv = tennv;
        this.diachi = diachi;
        this.gioitinh = gioitinh;
    }
    
    

    public NhanVien(int manv, String tennv, String diachi, String gioitinh) {
       this.manv = manv;
       this.tennv = tennv;
       this.diachi = diachi;
       this.gioitinh = gioitinh;
    }
   
    public int getManv() {
        return this.manv;
    }
    
    public void setManv(int manv) {
        this.manv = manv;
    }
    public String getTennv() {
        return this.tennv;
    }
    
    public void setTennv(String tennv) {
        this.tennv = tennv;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public String getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }




}


